-- VerifiedPulse Supabase Schema
-- Run this in the Supabase SQL Editor (Dashboard -> SQL Editor)

CREATE TABLE IF NOT EXISTS public.checks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim TEXT NOT NULL,
  mode TEXT NOT NULL DEFAULT 'text',
  propositions TEXT NOT NULL,
  conjunction_result INTEGER NOT NULL DEFAULT 0,
  search_evidence TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.providers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  model TEXT NOT NULL,
  calls INTEGER NOT NULL DEFAULT 0,
  successes INTEGER NOT NULL DEFAULT 0,
  failures INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  last_used TIMESTAMPTZ,
  rate_limit_count INTEGER NOT NULL DEFAULT 0,
  suspended_until TIMESTAMPTZ
);

-- Misinformation tracking tables for social network spread analysis

-- Track flagged misinformation claims and their propagation across social platforms
CREATE TABLE IF NOT EXISTS public.misinformation_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim TEXT NOT NULL,
  claim_hash TEXT NOT NULL,
  conjunction_result INTEGER NOT NULL DEFAULT 0,
  misinformation_risk_score INTEGER NOT NULL DEFAULT 0, -- 0-100
  platform TEXT NOT NULL, -- 'twitter', 'facebook', 'tiktok', 'whatsapp', 'telegram', 'reddit', 'other'
  shares INTEGER NOT NULL DEFAULT 0,
  impressions INTEGER NOT NULL DEFAULT 0,
  engagement_rate NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  spread_velocity NUMERIC(8,2) NOT NULL DEFAULT 0.00, -- shares per hour
  detection_timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reported_at TIMESTAMPTZ,
  fact_check_id BIGINT REFERENCES public.checks(id) ON DELETE SET NULL,
  is_resolved BOOLEAN NOT NULL DEFAULT false,
  resolution_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Track social network propagation paths for misinformation
CREATE TABLE IF NOT EXISTS public.misinformation_spread (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES public.misinformation_events(id) ON DELETE CASCADE,
  source_platform TEXT NOT NULL,
  target_platform TEXT NOT NULL,
  cross_shares INTEGER NOT NULL DEFAULT 0,
  propagation_speed NUMERIC(8,2) NOT NULL DEFAULT 0.00,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Track platform-specific misinformation statistics
CREATE TABLE IF NOT EXISTS public.platform_misinformation_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform TEXT NOT NULL UNIQUE,
  total_misinformation_events INTEGER NOT NULL DEFAULT 0,
  total_shares INTEGER NOT NULL DEFAULT 0,
  total_impressions INTEGER NOT NULL DEFAULT 0,
  avg_misinformation_risk_score NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  avg_spread_velocity NUMERIC(8,2) NOT NULL DEFAULT 0.00,
  last_updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_checks_created_at ON public.checks(created_at);
CREATE INDEX IF NOT EXISTS idx_checks_mode ON public.checks(mode);
CREATE INDEX IF NOT EXISTS idx_misinformation_events_claim_hash ON public.misinformation_events(claim_hash);
CREATE INDEX IF NOT EXISTS idx_misinformation_events_platform ON public.misinformation_events(platform);
CREATE INDEX IF NOT EXISTS idx_misinformation_events_detection_timestamp ON public.misinformation_events(detection_timestamp);
CREATE INDEX IF NOT EXISTS idx_misinformation_events_risk_score ON public.misinformation_events(misinformation_risk_score);
CREATE INDEX IF NOT EXISTS idx_misinformation_spread_event_id ON public.misinformation_spread(event_id);
CREATE INDEX IF NOT EXISTS idx_platform_stats_platform ON public.platform_misinformation_stats(platform);

ALTER TABLE public.checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.misinformation_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.misinformation_spread ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.platform_misinformation_stats ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role can manage checks"
  ON public.checks FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Service role can manage providers"
  ON public.providers FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Service role can manage misinformation events"
  ON public.misinformation_events FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Service role can manage misinformation spread"
  ON public.misinformation_spread FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Service role can manage platform misinformation stats"
  ON public.platform_misinformation_stats FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');