-- VerifiedPulse Supabase Schema
-- Run this in the Supabase SQL Editor (Dashboard -> SQL Editor)

CREATE TABLE IF NOT EXISTS public.checks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim TEXT NOT NULL,
  mode TEXT NOT NULL DEFAULT 'text',
  propositions TEXT NOT NULL,
  conjunction_result INTEGER NOT NULL DEFAULT 0,
  search_evidence TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.providers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  model TEXT NOT NULL,
  calls INTEGER NOT NULL DEFAULT 0,
  successes INTEGER NOT NULL DEFAULT 0,
  failures INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  last_used TIMESTAMPTZ,
  rate_limit_count INTEGER NOT NULL DEFAULT 0,
  suspended_until TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_checks_created_at ON public.checks(created_at);
CREATE INDEX IF NOT EXISTS idx_checks_mode ON public.checks(mode);

ALTER TABLE public.checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.providers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role can manage checks"
  ON public.checks FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Service role can manage providers"
  ON public.providers FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');
